jobs:
  include:
    - stage: Deploy GitHub Release
      script:
        zip -r src.zip .
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "nam20485"
        - git config --local user.email "nathan.miller@hackoregon.org"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key:
          secure: oaoRtTE3Ryr9jKu83D5PxoQB2ufJ2fYzGnG2qKO384KFHY4Qbs7iCEsa4cehysi3VV35eRtvDx+KL283grVcbFIIVgr90V6RHJRQzmL77tsTO3sU5Uqm8IDJTD9gmidGS7piOdjOeytxh3iljesRxTmbkLMOyxMADLD/IIfD/aEIvs+gNt0r/8DsTYh7um5r+zxUV4MeXKRs5EOPKoZ5oL3TJ8kIdHeFrlzf8QW1AHmBxk6dzPQoSmBfPZyNkhR9+99HvMoDFRC09PDZbzKeCGFNOAWrSkexAqb3nELr+F3CDmvpHn8nmeV16fza1KpRlgEI/qLAVQbuSs9n55e9J/Xj39wUYV5vQ3SJZBx+fowEG3vAwlh7I7jJxDveiLJFxCb8l40igPJ5G17AowZIylILRAmslXDFcAFpLmMKiyjqHyNtc9R8L0wmnlriuRMF8PaG3wrA/1CitjWFMv58drlFBROSR6mzdcYktZVYUoz8XEYlGeyvblt+pqVgSDs6VYu6sb1WMTxhoO4uWMvAqvVjPuwLGp1wg6KfhkYSmTFFu7ySTjIsYf6CV9Q1ZGkhRBSlWQnYFrESeO8yuFiVxUtveTzZk8WQI8S75cfxWl55nd76HtrBRf4Rz1I2Sjt4hS3Ast67VsHJ0DzekLA7G3vDVQbW5s+qJx+jLU3NBHU=
        skip_cleanup: true
        file: src.zip
        on:
          tags: true
          #repo: hackoregon/2019-sandbox-backend
          #branch: develop
    #- stage: Deploy PyPI Release    
